Update README.md
ESIPFed/Geoweaver pull request #462
Opened 2024-03-05 07:05 UTC by JYOSHREDDY

features of Geoweaver added in the README.md file

2024-03-05 17:44 UTC, ZihengSun commented on README.md
> +4) Supports CRON executions
@JYOSHREDDY can you expand what CRON is?

2024-03-05 17:51 UTC, gokulprathin8 commented
I can jointly work on this with @JYOSHREDDY 
to redo the entire README to make it a bit more modern.

Please reach out to me at your convenient time @ slack to discuss and improve the overall readme file.

2024-03-05 19:02 UTC, gokulprathin8 commented
Here is the outline we discussed about
https://docs.google.com/document/d/1ATng4rOhrOTIGIEGprWgKy7MAbm0yz_AGkmtCDhPEZ8/edit?usp=sharing

please feel free to make changes if you feel there is a better way of doing it
also remove Circle CI passing badge and needs to be changed to Github Actions
since we are no longer using circle ci

2024-03-05 19:03 UTC, ZihengSun commented
@gokulprathin8 yeah, that is good. Although could you please help @JYOSHREDDY to merge this PR first and file another issue to completely refactor the README. It think that one will take longer than this PR

2024-03-05 19:04 UTC, gokulprathin8 commented
ok

2024-03-10 21:49 UTC, ZihengSun commented on README.md
> +4) Supports scheduling jobs / executions to run at specific times, dates and intervals using CRON for automation tasks.
I mean you need to add the full explained name of CRON. For people outside computer science, they have no idea what CRON is.

2024-03-10 21:49 UTC, ZihengSun requested changes
Another comment

2024-03-17 15:22 UTC, gokulprathin8 requested changes

2024-03-17 15:22 UTC, gokulprathin8 commented on README.md
> +![Screen Recording 2024-03-16 at 11 19 55 PM](https://github.com/JYOSHREDDY/Geoweaver/assets/102822880/8d6fb615-1430-4fe5-9728-e99586c9fd2a)
The processes in the video are failing. Please use a different worklfow, the SWE workflow has a few dependencies / assets on an external server which require you to download a few gigs of files.

Also, the recording source should be ESIPFed repo, as of now it is coming from your github account. Please verify

2024-03-17 16:14 UTC, gokulprathin8 commented
lets push this and make additional changes to the issue https://github.com/ESIPFed/Geoweaver/issues/463
and open a new PR to address new changes, this PR has been open for a while.

2024-03-17 16:15 UTC, gokulprathin8 commented
@JYOSHREDDY 
please open a new PR for https://github.com/ESIPFed/Geoweaver/issues/463

2024-03-17 16:15 UTC, merged