Navigation fix for process tab and workflow tab in Guide page
ESIPFed/Geoweaver pull request #472
Opened 2024-03-09 01:28 UTC by meghanakr7

Fix for [#471](https://github.com/ESIPFed/Geoweaver/issues/471)

2024-03-09 21:37 UTC, gokulprathin8 commented
@meghanakr7  the `New Process` and `Add to Weaver` styled buttons on the same `geoweaver.html` file have duplicate ids on them. This can cause weird behavior
we either need to remove the ids or make the buttons trigger the dialog.

2024-03-10 13:29 UTC, ZihengSun commented on src/main/resources/templates/geoweaver.html
> +					<div id="right-page-div" class="row" style="height:100%; left:0; margin:0; padding: 0;padding-bottom:0px;">
Cannot scroll to the bottom. The -50px is to ensure all the page content can be seen.

2024-03-10 13:29 UTC, ZihengSun requested changes
One comment

2024-03-12 04:32 UTC, meghanakr7 commented
> One comment

Reverted change related to height.

2024-03-17 15:19 UTC, gokulprathin8 requested changes

2024-03-17 15:19 UTC, gokulprathin8 commented on src/main/resources/templates/geoweaver.html
> +			<div class="row" id="site_main_div" style="height:calc(100vh); top: 80px; margin: 0px; padding: 0px; padding-top: 1px; width:100%; flex-shrink: 0; flex-basis: auto;">
Clicking on process / workflow hides the top navigation bar. Please recheck css

2024-03-17 22:22 UTC, gokulprathin8 commented
this fixes the view port to display content at 100% vh, please open a different PR to address the issue of fixing top nav being hidden for `top_nav` div

@meghanakr7

2024-03-17 22:22 UTC, gokulprathin8 approved these changes

2024-03-17 22:22 UTC, merged