Update README.md
ESIPFed/Geoweaver pull request #477
Opened 2024-03-18 05:55 UTC by JYOSHREDDY

1) Created a link pointing to Pygeoweaver encoraging people with python background to check that repo.
2) Created a link to check out the new website - https://geoweaver.dev/ — features of geoweaver.

2024-03-19 01:35 UTC, JYOSHREDDY commented
3) Added a Geoweaver banner.

2024-05-08 03:17 UTC, ZihengSun commented on README.md
> +# Geoweaver Installation Guide
please keep this installation guide as usual. Don't add these detailed steps in the front page. When people are interested, they should click on the install guide link which was here.

2024-05-08 03:18 UTC, ZihengSun requested changes
Don't add detailed steps. Restored the old links to the separated markdown docs.

2024-05-24 02:54 UTC, ZihengSun approved these changes
LG

2024-05-24 02:54 UTC, merged