updated documentation with port-listening
ESIPFed/Geoweaver pull request #535
Opened 2024-06-17 17:09 UTC by VisheshSaluja

2024-06-17 17:21 UTC, ZihengSun requested changes
comments

2024-06-17 17:21 UTC, ZihengSun commented on docs/install.md
> +Run the above command in a new terminal and then rebuild the application to start a new instance of Geoweaver running on your machine.
No you shouldn't `rebuild` the application. Just directly run the geoweaver using the start command. Please revise.

2024-06-17 18:38 UTC, ZihengSun commented on docs/install.md
> +Run the command above in a new terminal, then start the application(using start command) to launch a new instance of Geoweaver on your machine.
can you list what the start command is?

2024-06-17 18:38 UTC, ZihengSun requested changes
BTY

2024-06-18 00:22 UTC, VisheshSaluja commented on docs/install.md
> +Run the command above in a new terminal, then start the application(using start command) to launch a new instance of Geoweaver on your machine.
@ZihengSun please check

2024-06-19 15:57 UTC, ZihengSun approved these changes
LG

2024-06-19 16:28 UTC, merged