console log
ESIPFed/Geoweaver pull request #570
Opened 2024-10-11 04:41 UTC by VisheshSaluja

fixed for processes individually - process.js

fixing for process in workflow - process.sidepanel.js

2024-10-16 20:30 UTC, VisheshSaluja commented
### How to Test:

1. **Create a Workflow:**
   - Add two processes.

2. **Example Code for the Processes:**

   ```python
   import time

   def process_1():
       while True:
           print("Process 1: Still running...")
           time.sleep(2)  # Simulate work

   if __name__ == "__main__":
       process_1()


### Test

- Run a process.
- Check if the output of the first process(while in execution) is being rendered in the console log of second process or not.
- Also make some other checks, which might break something

2024-10-17 13:45 UTC, ZihengSun commented on src/main/resources/static/js/gw.ssh.js
> +      // console.log(err);
remove these commented out code

2024-10-17 13:46 UTC, ZihengSun commented on src/main/resources/static/js/gw.ssh.js
> +ws_onmessage: function (e) {
why is this function having the same name as the other function?

2024-10-17 13:46 UTC, ZihengSun requested changes
some comments

2024-10-17 22:27 UTC, VisheshSaluja commented
will fix this and also found another bug, will fix that as well

2024-10-23 15:24 UTC, closed without merging